apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: renovate-scheduler
subjects:
  - kind: ServiceAccount
    name: renovate-scheduler
roleRef:
  kind: Role
  name: renovate-scheduler
  apiGroup: rbac.authorization.k8s.io
