apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio
  namespace: default
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: minio
    app.kubernetes.io/managed-by: kustomize
