apiVersion: apps/v1
kind: Deployment
metadata:
  name: renovate-scheduler
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: renovate-scheduler
          env:
            - name: VAULT_ADDR
              value: "http://vault-amer.corp.adobe.com"
            - name: VAULT_ROLE_ID
              valueFrom:
                secretKeyRef:
                  name: renovate-vault
                  key: role_id
            - name: VAULT_SECRET_ID
              valueFrom:
                secretKeyRef:
                  name: renovate-vault
                  key: secret_id
            - name: REDIS_HOST
              value: redis-master:6379/0
            - name: REDIS_PASSWORD
              value: vault:secret/data/redis#password
